
planet-parameters:
  background-gas: N2
  surface-pressure: 1.013 # bar
  surface-gravity: 980.7 # cm/s^2
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm
  surface-albedo: 0.25 
  
boundary-conditions:
  - name: O2
    lower-boundary:
      mixing-ratio: 0.21
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H2
    lower-boundary:
      mixing-ratio: 5.3E-07
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CO2
    lower-boundary:
      mixing-ratio: 3.6E-4
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CH4
    lower-boundary:
      mixing-ratio: 1.8e-6
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CO
    lower-boundary:
      mixing-ratio: 1.1e-7
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: N2O
    lower-boundary:
      mixing-ratio: 3.1e-7
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
        